Bundler version
```
Run gem install bundler --version 2.5
Successfully installed bundler-2.5.0
1 gem installed
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
ArgumentError: Malformed version number string 2.4.12
   2.4.22
   2.5.7
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/rubygems/version.rb:223:in `initialize'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/rubygems/version.rb:206:in `new'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/rubygems/version.rb:206:in `new'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/self_manager.rb:165:in `lockfile_version'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/self_manager.rb:89:in `autoswitching_applies?'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/self_manager.rb:79:in `needs_switching?'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/self_manager.rb:10:in `restart_with_locked_bundler_if_needed'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:67:in `initialize'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:388:in `new'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:388:in `dispatch'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle:25:in `load'
  /opt/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle:25:in `<main>'
```