[#0] Resolve file path conflict
See sister commit 1ad53024.

e.g.

```
Git command failed:
error: The following untracked working tree files would be overwritten
by checkout:
docs/api/postman.md
Please move or remove them before you switch branches.
Aborting
```